# Stage 1: Build the API project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the entire solution
COPY . .

# Restore dependencies and publish the API project
RUN dotnet publish ./FoodTracker.Web.API/FoodTracker.Web.API.csproj -c Release -o /app/publish
   
# Stage 2: Run the API project
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "FoodTracker.Web.API.dll"]
