services:
  api:
    image: ucciregistry.azurecr.io/foodtracker-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__FoodTrackerDb=Server=db;Database=FoodTracker;Trusted_Connection=False;User=sa;Password=YourStrong@Passw0rd;encrypt=false
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app-network

  ui:
    image: ucciregistry.azurecr.io/foodtracker-webui
    networks:
      - app-network
    volumes:
      - ui-build:/app

  db:
    image: ucciregistry.azurecr.io/foodtracker-db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    # ports:
    #   - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - app-network

  nginx:
    image: ucciregistry.azurecr.io/foodtracker-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ui-build:/usr/share/nginx/html:ro
    ports:
      - "8181:80"
    depends_on:
      - api
      - ui
    networks:
      - app-network

volumes:
  sqlvolume:
  ui-build:

networks:
  app-network:
    driver: bridge
