version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__FoodTrackerDb=Server=db;Database=FoodTracker;Trusted_Connection=False;User=sa;Password=YourStrong@Passw0rd;encrypt=false
    depends_on:
      - db
    networks:
      - app-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    networks:
      - app-network
    volumes:
      - ui-build:/app

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    # ports:
    #   - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ui-build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - ui
    networks:
      - app-network

volumes:
  sqlvolume:
  ui-build:

networks:
  app-network:
    driver: bridge
